# Enable compile command to ease indexing with e.g. clangd
set(CMAKE_EXPORT_COMPILE_COMMANDS TRUE)

# Compiler options
target_compile_options(${BUILD_UNIT_0_NAME} PRIVATE
    $<$<COMPILE_LANGUAGE:C>: ${CUBE_CMAKE_C_FLAGS}>
    $<$<COMPILE_LANGUAGE:CXX>: ${CUBE_CMAKE_CXX_FLAGS}>
    $<$<COMPILE_LANGUAGE:ASM>: ${CUBE_CMAKE_ASM_FLAGS}>
)

# Linker options
target_link_options(${BUILD_UNIT_0_NAME} PRIVATE ${CUBE_CMAKE_EXE_LINKER_FLAGS})

# Add sources to executable/library
target_sources(${BUILD_UNIT_0_NAME} PRIVATE
    "Core/Src/app_entry.c"
    "Core/Src/dht11.c"
    "Core/Src/main.c"
    "Core/Src/stm32wbaxx_hal_msp.c"
    "Core/Src/stm32wbaxx_it.c"
    "Application/User/Core/syscalls.c"
    "Application/User/Core/sysmem.c"
    "STM32_WPAN/App/app_zigbee.c"
    "STM32_WPAN/App/app_zigbee_endpoint.c"
    "STM32_WPAN/App/app_zigbee_utility.c"
    "STM32_WPAN/Target/linklayer_plat.c"
    "STM32_WPAN/Target/ll_sys_if.c"
    "STM32_WPAN/Target/mac_sys_if.c"
    "STM32_WPAN/Target/power_table.c"
    "STM32_WPAN/Target/zigbee_plat.c"
    "STM32_WPAN/Target/zigbee_sys_if.c"
    "Application/User/Startup/startup_stm32wba55cgux.s"
    "System/Config/CRC_Ctrl/crc_ctrl_conf.c"
    "System/Config/Debug_GPIO/app_debug.c"
    "System/Config/LowPower/peripheral_init.c"
    "System/Config/LowPower/user_low_power_config.c"
    "System/Interfaces/stm32_lpm_if.c"
    "Projects/Common/WPAN/Interfaces/adv_trace_usart_if.c"
    "Projects/Common/WPAN/Interfaces/app_bsp.c"
    "Projects/Common/WPAN/Interfaces/hw_aes.c"
    "Projects/Common/WPAN/Interfaces/hw_rng.c"
    "Projects/Common/WPAN/Interfaces/timer_if.c"
    "Projects/Common/WPAN/Modules/BasicAES/baes_ccm.c"
    "Projects/Common/WPAN/Modules/BasicAES/baes_cmac.c"
    "Projects/Common/WPAN/Modules/BasicAES/baes_ecb.c"
    "Projects/Common/WPAN/Modules/Log/log_module.c"
    "Projects/Common/WPAN/Modules/RFControl/rf_antenna_switch.c"
    "Projects/Common/WPAN/Modules/RTDebug/RTDebug.c"
    "Projects/Common/WPAN/Modules/RTDebug/RTDebug_dtb.c"
    "Projects/Common/WPAN/Modules/SerialCmdInterpreter/serial_cmd_interpreter.c"
    "Projects/Common/WPAN/Modules/app_sys.c"
    "Projects/Common/WPAN/Modules/crc_ctrl.c"
    "Projects/Common/WPAN/Modules/otp.c"
    "Projects/Common/WPAN/Modules/scm.c"
    "Projects/Common/WPAN/Modules/stm_list.c"
    "Projects/Common/WPAN/Startup/stm32wbaxx_ResetHandler_GCC.s"
    "readme.md"
    "Drivers/BSP/STM32WBAxx_Nucleo/stm32wbaxx_nucleo.c"
    "Core/Src/system_stm32wbaxx.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_adc.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_adc_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_comp.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_cortex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_crc.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_crc_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_cryp.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_cryp_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_dma.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_dma_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_exti.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_flash.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_flash_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_gpio.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_gtzc.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_hash.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_hsem.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_i2c.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_i2c_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_icache.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_irda.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_iwdg.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_lptim.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_pka.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_pwr.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_pwr_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_ramcfg.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rcc.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rcc_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rng.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rng_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rtc.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_rtc_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_sai.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_sai_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_smartcard.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_smartcard_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_smbus.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_smbus_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_spi.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_spi_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_tim.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_tim_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_tsc.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_uart.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_uart_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_usart.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_usart_ex.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_hal_wwdg.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_ll_rcc.c"
    "Drivers/STM32WBAxx_HAL_Driver/Src/stm32wbaxx_ll_tim.c"
    "Middlewares/ST/STM32_WPAN/link_layer/ll_sys/src/ll_sys_cs.c"
    "Middlewares/ST/STM32_WPAN/link_layer/ll_sys/src/ll_sys_dp_slp.c"
    "Middlewares/ST/STM32_WPAN/link_layer/ll_sys/src/ll_sys_intf.c"
    "Middlewares/ST/STM32_WPAN/link_layer/ll_sys/src/ll_sys_startup.c"
    "Utilities/trace/adv_trace/stm32_adv_trace.c"
    "Utilities/lpm/tiny_lpm/stm32_lpm.c"
    "Utilities/misc/stm32_mem.c"
    "Utilities/sequencer/stm32_seq.c"
    "Utilities/tim_serv/stm32_timer.c"
    "Utilities/misc/stm32_tiny_vsnprintf.c"
)

target_include_directories(${BUILD_UNIT_0_NAME} PRIVATE
    "Core/Inc"
    "STM32_WPAN/App"
    "STM32_WPAN/Target"
    "System/Config/CRC_Ctrl"
    "System/Config/Debug_GPIO"
    "System/Config"
    "System/Config/Log"
    "System/Config/LowPower"
    "System/Interfaces"
    "Projects/Common/WPAN/Interfaces"
    "Projects/Common/WPAN/Modules"
    "Projects/Common/WPAN/Modules/BasicAES"
    "Projects/Common/WPAN/Modules/Flash"
    "Projects/Common/WPAN/Modules/Log"
    "Projects/Common/WPAN/Modules/MemoryManager"
    "Projects/Common/WPAN/Modules/RTDebug"
    "Projects/Common/WPAN/Modules/SerialCmdInterpreter"
    "Drivers/CMSIS/Include"
    "Drivers/CMSIS/Device/ST/STM32WBAxx/Include"
    "Drivers/STM32WBAxx_HAL_Driver/Inc"
    "Drivers/BSP/Components/Common"
    "Drivers/BSP/STM32WBAxx_Nucleo"
    "Middlewares/ST/STM32_WPAN"
    "Middlewares/ST/STM32_WPAN/zigbee/include"
    "Middlewares/ST/STM32_WPAN/zigbee/stack/include"
    "Middlewares/ST/STM32_WPAN/zigbee/stack/port/stm32wba"
    "Middlewares/ST/STM32_WPAN/zigbee/stack/port/mac"
    "Middlewares/ST/STM32_WPAN/mac_802_15_4/core/inc"
    "Middlewares/ST/STM32_WPAN/link_layer/ll_sys/inc"
    "Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/config/ieee_15_4_basic"
    "Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc"
    "Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/inc/ot_inc"
    "Middlewares/ST/STM32_WPAN/utilities"
    "Middlewares/ST/STM32_WPAN/interface"
    "Utilities/conf"
    "Utilities/lpm/tiny_lpm"
    "Utilities/misc"
    "Utilities/sequencer"
    "Utilities/tim_serv"
    "Utilities/trace/adv_trace"
)

configure_file("${CMAKE_SOURCE_DIR}/STM32WBA55CGUX_FLASH.ld" "${CMAKE_BINARY_DIR}" COPYONLY)

set(CMAKE_C_LINK_GROUP_USING_cross_refs_0_SUPPORTED TRUE)
set(CMAKE_CXX_LINK_GROUP_USING_cross_refs_0_SUPPORTED TRUE)
set(CMAKE_C_LINK_GROUP_USING_cross_refs_0
    "LINKER:--start-group"
    "LINKER:--end-group"
)
set(CMAKE_CXX_LINK_GROUP_USING_cross_refs_0
    "LINKER:--start-group"
    "LINKER:--end-group"
)

target_link_libraries(${BUILD_UNIT_0_NAME}
    "$<LINK_GROUP:cross_refs_0"
    "${CMAKE_SOURCE_DIR}/Middlewares/ST/STM32_WPAN/link_layer/ll_cmd_lib/lib/WBA5_LinkLayer15_4.a"
    "${CMAKE_SOURCE_DIR}/Middlewares/ST/STM32_WPAN/mac_802_15_4/lib/wba_mac_lib.a"
    "${CMAKE_SOURCE_DIR}/Middlewares/ST/STM32_WPAN/zigbee/clusters/ZigBeeClusters.a"
    "${CMAKE_SOURCE_DIR}/Middlewares/ST/STM32_WPAN/zigbee/stack/ZigBeeProR23_FFD.a"
    ">"
)

set_target_properties(${BUILD_UNIT_0_NAME} PROPERTIES LINK_DEPENDS "STM32WBA55CGUX_FLASH.ld")

